apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: audi 
  janus-idp.io/tekton: audi
  backstage.io/kubernetes-id: audi
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: audi
resources: 
- application-dev.yaml