apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: audi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audi 
  name: audi
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: audi 
    weight: 100 
  wildcardPolicy: None
